var fluidAuthor = [//var fluidAuthor = 
	{	
		author_img:'img/author/1(1).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(2).jpg',
		author_name:'小亲亲',
		tag_box:['html','css'],
		author_state:'资深测试开发，多次带领团队解决自动化相关技术难点，多年web自动化、性能测试经验，负责研发过多款接口自动化测试框架。'
	},
	{
		author_img:'img/author/1(3).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript','ajax'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(4).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(5).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'阿里资深研发，主要从事移动端、前端工作。工作之余喜欢写博客，潜心修炼技术，励志做一名有“文化”的技术人。'
	},
	{
		author_img:'img/author/1(6).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(7).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(8).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(9).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(10).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(11).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(12).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(13).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(14).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(15).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(16).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(17).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(18).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(19).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(20).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{	
		author_img:'img/author/1(1).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(2).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(3).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(4).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(5).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(6).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(7).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(8).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(9).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(10).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(11).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(12).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(13).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(14).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(15).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(16).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(17).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(18).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(19).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(20).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(8).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(9).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(10).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(11).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(12).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(13).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(14).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(15).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},{
		author_img:'img/author/1(8).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(9).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(10).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(11).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(12).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(13).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(14).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		author_img:'img/author/1(15).jpg',
		author_name:'小亲亲',
		tag_box:['html','css','javascript'],
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	}
];