var fluid = [
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(1).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(1).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(2).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(2).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(3).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(3).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(4).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(4).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(5).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(5).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(6).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(6).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(7).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(7).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(8).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(8).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(9).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(9).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(10).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(10).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(11).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(11).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(12).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(12).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(14).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(14).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(15).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(15).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(16).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(16).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(17).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(17).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(18).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(18).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(19).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(19).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(20).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(20).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(1).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(1).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(2).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(2).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(3).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(3).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(4).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(4).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(5).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(5).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(6).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(6).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(7).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(7).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(8).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(8).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(9).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(9).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(10).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(10).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(11).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(11).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(12).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(12).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(13).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(13).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(14).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(14).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(15).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(15).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(16).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(16).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(17).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(17).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(18).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(18).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(19).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(19).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(20).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(20).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(8).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(8).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(9).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(9).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(10).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(10).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(11).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(11).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(12).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(12).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(13).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(13).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(14).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(14).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(15).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(15).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(16).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(16).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(17).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(17).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(18).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(18).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	},
	{
		name:'小亲亲',
		item_img:'img/boxImg/1(19).jpg',
		dialog_txt:'最时尚的毛衣',
		dialog_span:'时尚时尚最时尚的毛衣，你有了吗',
		head:'img/author/1(19).jpg',
		name:'double小亲亲',
		state:'做美女，舒适最重要',
		author_state:'&nbsp;时尚设计师、服装搭配师、蘑菇街时尚买手<br>&nbsp;喜欢远足、喜欢摄影、喜欢手绘'
	}
];